name: Build gem

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "jruby-9.2.9.0"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Execute tests
        run: bundle exec rake

      - name: Build ruby GEM
        working-directory: ./main
        run: gem build logstash-output-mongodb.gem

      - name: Upload GEM as a build artifact
        uses: actions/upload-artifact@v3
        with:
          name: logstash-output-mongodb.gem
          path: ./logstash-output-mongodb.gem
