name: Build gem

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOGSTASH_PATH: ${{ github.workspace }}/logstash
      LOGSTASH_SOURCE: "1"
      OSS: "true"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout logstash repo
        uses: actions/checkout@v3
        with:
          repository: elastic/logstash
          ref: "v8.8.1"
          path: logstash
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: "Install logstash dependencies (https://github.com/elastic/logstash/tree/v8.8.1#building-logstash)"
        working-directory: ./logstash
        run: ./gradlew assemble

      - name: Setup JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "jruby-9.2.9.0"
          working-directory: ./main
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Execute tests
        working-directory: ./main
        run: bundle exec rspec

      - name: Build ruby GEM
        working-directory: ./main
        run: gem build logstash-output-mongodb

      - name: Upload GEM as a build artifact
        uses: actions/upload-artifact@v3
        with:
          name: logstash-output-mongodb.gem
          path: ./main/logstash-output-mongodb-*.gem
